name: CI
on: [push, pull_request]

jobs:
  unit-tests:
    name: Unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies on macOS
        run: |
          set -x
          brew install shellcheck python3
          pip3 install pyflakes
          shellcheck --version
          pyflakes --version
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Install dependencies on Linux
        run: |
          set -x
          sudo apt install shellcheck
          pip install pyflakes
          shellcheck --version
          pyflakes --version
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Install dependencies on Windows
        run: |
          # `choco install shellcheck` is too slow on GitHub Actions. It takes more than 3 minutes to install one package
          # choco install shellcheck
          pip install pyflakes
          pyflakes --version
        if: ${{ matrix.os == 'windows-latest' }}
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: go build ./cmd/actionlint
        env:
          # Note: -race requires cgo
          CGO_ENABLED: 0
      - run: go test -v -race -coverprofile coverage.txt -covermode=atomic ./ ./scripts/...
      - run: go tool cover -func ./coverage.txt
      # Dog fooding ðŸ¶
      - run: ./actionlint -color
      - uses: codecov/codecov-action@v2
        with:
          env_vars: OS
        env:
          OS: ${{ matrix.os }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Check Go sources are formatted
        run: |
          diffs="$(gofmt -d ./*.go ./cmd/actionlint/*.go ./scripts/*/*.go ./playground/*.go)"
          if [[ "$diffs" != "" ]]; then
            echo "$diffs" >&2
            exit 1
          fi
      - name: Install staticcheck
        run: |
          go get honnef.co/go/tools/cmd/staticcheck@latest
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - run: make lint
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - name: Check playground files
        run: |
          cd ./playground
          set -x
          make main.wasm
          npm install
          npm run lint
      - name: Lint bash scripts
        run: shellcheck ./scripts/download-actionlint.bash ./playground/post-install.bash ./playground/deploy.bash
